FROM bats/bats:latest

ARG CONTAINER_PROJECT_ROOT_NAME
ENV CONTAINER_PROJECT_ROOT_NAME=${CONTAINER_PROJECT_ROOT_NAME}
ENV SRC_CODE_PATH="/code/${CONTAINER_PROJECT_ROOT_NAME}"

ARG N2ST_BATS_TESTING_TOOLS_RELATIVE_PATH
ENV N2ST_BATS_TESTING_TOOLS_RELATIVE_PATH=${N2ST_BATS_TESTING_TOOLS_RELATIVE_PATH:?'Build argument needs to be set and non-empty.'}

ARG TEAMCITY_VERSION
ENV TEAMCITY_VERSION=${TEAMCITY_VERSION}

ARG N2ST_VERSION
LABEL norlab.tools.norlab-shell-script-tools.tester="${N2ST_VERSION:?err}"
LABEL org.opencontainers.image.authors="luc.coupal.1@ulaval.ca"

SHELL ["/bin/bash", "-e", "-c"]
ARG DEBIAN_FRONTEND=noninteractive

ENV TERM=${TERM:-"xterm-256color"}
ENV COLUMNS=80

# Note:
#   Image purpose › source code isolation for CI build
#   This container use a copy project source code strategy instead of using the mounting volume

# ====Begin========================================================================================
RUN apk --no-cache add \
    git \
    tree

# ....Setup project source code....................................................................
COPY ./bats_helper_functions.bash $SRC_CODE_PATH/bats_testing_tools/bats_helper_functions.bash
#RUN chown -R $(whoami) $SRC_CODE_PATH

# ====End==========================================================================================
WORKDIR $SRC_CODE_PATH

ENTRYPOINT [ "/tini", "--", "bash", "bats", "--recursive", "--verbose-run", "--print-output-on-failure" ]
