FROM bats/bats:latest

ARG CONTAINER_PROJECT_ROOT_NAME
ENV CONTAINER_PROJECT_ROOT_NAME=${CONTAINER_PROJECT_ROOT_NAME}
ENV SRC_CODE_PATH="/code/${CONTAINER_PROJECT_ROOT_NAME}/"
ENV TERM=${TERM:-"xterm-256color"}

# Note:
#   Image purpose › source code isolation for CI build
#   This container use a copy project source code strategy instead of using the mounting volume

# ====Begin========================================================================================================
RUN apk --no-cache add \
    git \
    tree

COPY . $SRC_CODE_PATH
#RUN chown -R $(whoami) $SRC_CODE_PATH

# ====End==========================================================================================================
WORKDIR $SRC_CODE_PATH

ENTRYPOINT [ "/tini", "--", "bash", "bats" ]
